# Generated by Django 2.2.4 on 2019-08-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('storagedevice', '存储设备'), ('sanswitch', '光纤交换机')], default='storagedevice', max_length=64, verbose_name='资产类型')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='资产名称')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='资产序列号')),
                ('status', models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '故障'), (3, '备用'), (4, '未知')], default=0, verbose_name='设备状态')),
                ('tags', models.CharField(max_length=64, unique=True, verbose_name='资产标签')),
                ('idc', models.CharField(choices=[('nh1-1', '南汇1-1'), ('nh1-2', '南汇1-2'), ('nh2-1', '南汇2-1'), ('nh3-1', '南汇3-1'), ('zp', '周浦机房'), ('xj', '测试机房'), ('hf', '呼叫中心')], default='nh1-1', max_length=64)),
                ('cabinet', models.CharField(blank=True, max_length=64, null=True, verbose_name='机柜位置')),
                ('firmware', models.CharField(blank=True, max_length=128, null=True, verbose_name='固件版本')),
                ('purchase_day', models.DateField(blank=True, null=True, verbose_name='维保开始时间')),
                ('expire_day', models.DateField(blank=True, null=True, verbose_name='维保结束时间')),
            ],
            options={
                'verbose_name': '资产总表',
                'verbose_name_plural': '资产总表',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='厂商名称')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='支持电话')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '厂商',
                'verbose_name_plural': '厂商',
            },
        ),
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_asset_type', models.SmallIntegerField(choices=[(0, '统一存储'), (1, 'SAN存储'), (2, 'NAS存储'), (3, '备份存储')], default=0, verbose_name='存储类型')),
                ('model', models.CharField(default='未知型号', max_length=128, verbose_name='存储型号')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StorageInfo.Asset')),
            ],
            options={
                'verbose_name': '存储设备',
                'verbose_name_plural': '存储设备',
            },
        ),
        migrations.CreateModel(
            name='SanSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_asset_type', models.CharField(choices=[('24port', '24口光纤交换机'), ('48port', '48口光纤交换机'), ('96port', '96口光纤交换机')], default='24port', max_length=64, verbose_name='光纤交换机类型')),
                ('model', models.CharField(default='未知型号', max_length=128, verbose_name='光纤交换机型号')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StorageInfo.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StorageInfo.Manufacturer', verbose_name='制造商'),
        ),
    ]
