# Generated by Django 2.2.4 on 2019-08-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanswitch',
            options={'verbose_name': '光纤交换机', 'verbose_name_plural': '光纤交换机'},
        ),
        migrations.AddField(
            model_name='asset',
            name='mgt_ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='管理地址'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('storagedevice', '存储'), ('sanswitch', '光纤交换机')], default='storagedevice', max_length=64, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='idc',
            field=models.CharField(choices=[('nh11', '南汇1-1'), ('nh12', '南汇1-2'), ('nh21', '南汇2-1'), ('nh31', '南汇3-1'), ('zp', '周浦机房'), ('xj', '测试机房'), ('hf', '呼叫中心')], default='nh11', max_length=64, verbose_name='机房'),
        ),
    ]
