# Generated by Django 2.2.4 on 2019-08-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StorageInfo', '0002_auto_20190807_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='pinpai',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='品牌型号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StorageInfo.Manufacturer', verbose_name='维保商'),
        ),
    ]
