# Generated by Django 2.2.4 on 2019-08-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageInfo', '0004_auto_20190807_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': '维保厂商', 'verbose_name_plural': '维保厂商'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=64, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.CharField(max_length=64, verbose_name='资产标签'),
        ),
    ]
