# Generated by Django 2.2.4 on 2019-08-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageInfo', '0005_auto_20190808_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('storagedevice', '存储'), ('sanswitch', '光纤交换机')], max_length=64, verbose_name='资产类型'),
        ),
    ]
