# Generated by Django 2.2.4 on 2019-08-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageInfo', '0006_auto_20190808_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanswitch',
            name='model',
        ),
        migrations.RemoveField(
            model_name='storagedevice',
            name='model',
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pinpai',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='品牌'),
        ),
    ]
