# Generated by Django 2.2.4 on 2019-08-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageInfo', '0007_auto_20190809_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanswitch',
            name='domain_id',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Domain_ID'),
        ),
    ]
